name: Trigger auto deployment for limelight-api-server

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'docker/api-server/**'
    - '.github/workflows/limelight-api-server-AutoDeployTrigger-71943207-79d3-4983-99bb-0348259819dd.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: vscodedev.azurecr.io
          username: ${{ secrets.LIMELIGHTAPISERVER_REGISTRY_USERNAME }}
          password: ${{ secrets.LIMELIGHTAPISERVER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: vscodedev.azurecr.io/limelight-api-server:${{ github.sha }}
          file: ./docker/api-server/Dockerfile
          context: ./docker/api-server/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.LIMELIGHTAPISERVER_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n limelight-api-server -g limelight --server vscodedev.azurecr.io --username  ${{ secrets.LIMELIGHTAPISERVER_REGISTRY_USERNAME }} --password ${{ secrets.LIMELIGHTAPISERVER_REGISTRY_PASSWORD }}
            az containerapp update -n limelight-api-server -g limelight --image vscodedev.azurecr.io/limelight-api-server:${{ github.sha }}
